# Generated by Django 2.2.2 on 2019-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo2',
            name='option',
            field=models.IntegerField(default=0),
        ),
    ]
